#!/usr/bin/env python3
"""Battery health and remaining useful life analyzer.

This script analyzes historical battery data stored in CSV or JSON format and
estimates:
- Current SOH (State of Health)
- Degradation rates over time
- Cycle-based degradation trends
- Remaining useful life (RUL)
- Future SOH projection

Optional plots can also be generated if `matplotlib` is installed.

Requirements:
    pip install numpy pandas scipy matplotlib
"""

import argparse
import json
import warnings
from datetime import datetime, timedelta
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import curve_fit

warnings.filterwarnings("ignore")

class BatteryEstimator:
    """Estimate battery health metrics from historical measurements.

    The estimator supports CSV and JSON input files generated by the battery
    collection scripts in this project. It is also backward-compatible with the
    original Portuguese field names already present in existing datasets.
    """

    def __init__(self, data_file: str, file_type: str = "auto"):
        """Initialize the estimator with a historical battery dataset.

        Parameters
        ----------
        data_file:
            Path to a CSV or JSON file containing historical battery data.
        file_type:
            File type hint: `csv`, `json`, or `auto`.
        """
        self.data = self._load_data(data_file, file_type)
        self.estimates = {}
        
    def _load_data(self, data_file: str, file_type: str):
        """Load historical battery data from CSV or JSON."""
        data_file = Path(data_file)
        
        if file_type == 'auto':
            if data_file.suffix == '.csv':
                file_type = 'csv'
            elif data_file.suffix == '.json':
                file_type = 'json'
            else:
                raise ValueError(f"Unsupported format: {data_file.suffix}")
        
        if file_type == 'csv':
            df = pd.read_csv(data_file)
            # Convert timestamp to datetime if available.
            if 'timestamp' in df.columns:
                df['timestamp'] = pd.to_datetime(df['timestamp'])
            return df
        elif file_type == 'json':
            with open(data_file, 'r', encoding='utf-8') as file:
                data = json.load(file)
            if isinstance(data, list):
                df = pd.DataFrame(data)
            else:
                df = pd.DataFrame([data])
            if 'timestamp' in df.columns:
                df['timestamp'] = pd.to_datetime(df['timestamp'])
            return df
        else:
            raise ValueError(f"Invalid file type: {file_type}")
    
    def calculate_current_soh(self):
        """Calculate the current SOH using the most recent available record."""
        if self.data.empty:
            return None
        
        latest = self.data.iloc[-1]
        
        # Try multiple compatible field names from old and new datasets.
        if 'soh_percent' in latest and pd.notna(latest['soh_percent']):
            return float(latest['soh_percent'])
        elif 'soh_percentual' in latest and pd.notna(latest['soh_percentual']):
            return float(latest['soh_percentual'])
        elif 'current_full_energy_wh' in latest and 'design_energy_wh' in latest:
            soh = (latest['current_full_energy_wh'] / latest['design_energy_wh']) * 100
            return float(soh)
        elif 'energia_total_atual_wh' in latest and 'energia_design_wh' in latest:
            soh = (latest['energia_total_atual_wh'] / latest['energia_design_wh']) * 100
            return float(soh)
        elif 'current_full_charge_ah' in latest and 'design_charge_ah' in latest:
            soh = (latest['current_full_charge_ah'] / latest['design_charge_ah']) * 100
            return float(soh)
        elif 'carga_total_atual_ah' in latest and 'carga_design_ah' in latest:
            soh = (latest['carga_total_atual_ah'] / latest['carga_design_ah']) * 100
            return float(soh)
        else:
            # Fall back to a capacity field if available.
            capacity_value = latest.get('capacity_percent', latest.get('capacidade_percentual', None))
            return float(capacity_value) if pd.notna(capacity_value) else None
    
    def estimate_degradation_rate(self):
        """Estimate degradation rate using multiple fitted models.

        Returns
        -------
        dict | None
            Dictionary with linear, exponential, and cycle-based degradation
            estimates when enough data is available.
        """
        if self.data.empty:
            return None
        
        # Extract SOH values over time.
        soh_data = []
        time_data = []
        
        for idx, row in self.data.iterrows():
            soh = None
            if 'soh_percent' in row and pd.notna(row['soh_percent']):
                soh = float(row['soh_percent'])
            elif 'soh_percentual' in row and pd.notna(row['soh_percentual']):
                soh = float(row['soh_percentual'])
            elif 'current_full_energy_wh' in row and 'design_energy_wh' in row:
                soh = (row['current_full_energy_wh'] / row['design_energy_wh']) * 100
            elif 'energia_total_atual_wh' in row and 'energia_design_wh' in row:
                soh = (row['energia_total_atual_wh'] / row['energia_design_wh']) * 100
            elif 'current_full_charge_ah' in row and 'design_charge_ah' in row:
                soh = (row['current_full_charge_ah'] / row['design_charge_ah']) * 100
            elif 'carga_total_atual_ah' in row and 'carga_design_ah' in row:
                soh = (row['carga_total_atual_ah'] / row['carga_design_ah']) * 100
            
            if soh is not None and soh > 0:
                soh_data.append(soh)
                if 'timestamp' in row and pd.notna(row['timestamp']):
                    # Use total seconds since the first valid point.
                    if len(time_data) == 0:
                        start_time = row['timestamp']
                    seconds = (row['timestamp'] - start_time).total_seconds()
                    time_data.append(seconds)
                elif 'unix_timestamp' in row:
                    if len(time_data) == 0:
                        start_time = row['unix_timestamp']
                    seconds = float(row['unix_timestamp']) - float(start_time)
                    time_data.append(seconds)
                else:
                    time_data.append(float(idx))
        
        if len(soh_data) < 3:
            return None
        
        time_data = np.array(time_data, dtype=float)
        soh_data = np.array(soh_data, dtype=float)

        # If all time values are identical the system is degenerate — not enough
        # time variation to fit a trend.
        time_range = time_data[-1] - time_data[0]
        if time_range == 0:
            print("Note: All data points share the same timestamp — cannot estimate degradation rate.")
            print("      Collect data over a longer period (ideally 30+ days) for meaningful estimates.")
            return None

        # Convert seconds to days for reporting; keep raw seconds for fitting.
        time_days = time_data / 86400.0

        # Linear model: SOH = a * time + b
        try:
            linear_coef = np.polyfit(time_days, soh_data, 1)
        except np.linalg.LinAlgError:
            print("Note: Not enough variation in data to fit a linear model.")
            return None
        linear_rate = linear_coef[0]  # % per day
        linear_r2 = self._r_squared(soh_data, np.polyval(linear_coef, time_days))
        
        # Exponential model: SOH = a * exp(b * time) + c
        try:
            def exp_decay(t, a, b, c):
                return a * np.exp(b * t) + c
            
            # Initial guess.
            p0 = [soh_data[0] - 70, -0.001, 70]
            bounds = ([-np.inf, -np.inf, 0], [np.inf, 0, np.inf])
            exp_coef, _ = curve_fit(exp_decay, time_days, soh_data, p0=p0, bounds=bounds, maxfev=5000)
            exp_rate = exp_coef[1]
            exp_r2 = self._r_squared(soh_data, exp_decay(time_days, *exp_coef))
        except Exception:
            exp_rate = None
            exp_r2 = None
        
        # Cycle-based model when cycle count is available.
        cycle_data = []
        for idx, row in self.data.iterrows():
            cycle_value = row.get('cycle_count', row.get('ciclos', None))
            if pd.notna(cycle_value):
                cycles = float(cycle_value)
                soh = None
                if 'soh_percent' in row and pd.notna(row['soh_percent']):
                    soh = float(row['soh_percent'])
                elif 'soh_percentual' in row and pd.notna(row['soh_percentual']):
                    soh = float(row['soh_percentual'])
                if soh:
                    cycle_data.append((cycles, soh))
        
        cycle_rate = None
        cycle_r2 = None
        estimated_cycles_to_eol = None
        
        if len(cycle_data) > 2:
            cycles = np.array([c[0] for c in cycle_data])
            soh_cycles = np.array([c[1] for c in cycle_data])
            cycle_coef = np.polyfit(cycles, soh_cycles, 1)
            cycle_rate = cycle_coef[0]
            cycle_r2 = self._r_squared(soh_cycles, np.polyval(cycle_coef, cycles))
            
            # Cycles until end of life (SOH = 70%).
            if cycle_rate < 0:
                estimated_cycles_to_eol = (70 - cycle_coef[1]) / cycle_coef[0]
        
        return {
            'linear': {
                'rate_daily': linear_rate,
                'rate_monthly': linear_rate * 30,
                'rate_yearly': linear_rate * 365,
                'r2': linear_r2,
                'intercept': linear_coef[1]
            },
            'exponential': {
                'rate': exp_rate,
                'r2': exp_r2
            } if exp_rate else None,
            'cycle_based': {
                'rate_per_cycle': cycle_rate,
                'r2': cycle_r2,
                'estimated_cycles_to_eol': estimated_cycles_to_eol
            } if cycle_rate else None,
            'data_points': len(soh_data),
            'time_range_days': time_days[-1] - time_days[0] if len(time_days) > 1 else 0
        }
    
    def estimate_remaining_useful_life(self, eol_threshold: float = 70):
        """Estimate remaining useful life based on the linear degradation model.

        Parameters
        ----------
        eol_threshold:
            SOH percentage considered end of life.

        Returns
        -------
        dict | None
            Remaining life estimates in days, months, years, and projected EOL
            date.
        """
        current_soh = self.calculate_current_soh()
        if current_soh is None:
            return None
        
        degradation = self.estimate_degradation_rate()
        if degradation is None or degradation['linear']['rate_daily'] >= 0:
            return None
        
        rate = degradation['linear']['rate_daily']
        
        # Days until end of life.
        MAX_DAYS = 36500  # Cap at 100 years to avoid overflow in timedelta.
        if rate < 0:
            days_to_eol = (eol_threshold - current_soh) / rate
        else:
            days_to_eol = float('inf')

        days_finite = days_to_eol if days_to_eol != float('inf') else MAX_DAYS
        days_finite = min(days_finite, MAX_DAYS)

        try:
            eol_date = datetime.now() + timedelta(days=days_finite) if days_to_eol != float('inf') else None
        except (OverflowError, ValueError):
            eol_date = None
        
        return {
            'current_soh': current_soh,
            'eol_threshold': eol_threshold,
            'days_remaining': days_to_eol,
            'months_remaining': days_finite / 30,
            'years_remaining': days_finite / 365,
            'estimated_eol_date': eol_date,
            'degradation_rate_daily': rate,
            'degradation_rate_yearly': rate * 365
        }
    
    def predict_future_soh(self, days_ahead: int = 365):
        """Predict future SOH based on the linear degradation model."""
        degradation = self.estimate_degradation_rate()
        if degradation is None:
            return None
        
        current_soh = self.calculate_current_soh()
        if current_soh is None:
            return None
        
        rate = degradation['linear']['rate_daily']
        future_days = np.arange(0, days_ahead + 1)
        predicted_soh = current_soh + (rate * future_days)
        predicted_soh = np.maximum(predicted_soh, 0)
        
        return {
            'days': future_days,
            'soh': predicted_soh,
            'model': 'linear'
        }
    
    def get_statistics(self):
        """Generate descriptive statistics for the dataset."""
        if self.data.empty:
            return None
        
        stats_dict = {
            'period_start': self.data['timestamp'].min() if 'timestamp' in self.data.columns else None,
            'period_end': self.data['timestamp'].max() if 'timestamp' in self.data.columns else None,
            'total_samples': len(self.data),
            'total_cycles': None,
            'minimum_soh': None,
            'maximum_soh': None,
            'average_soh': None,
            'total_degradation': None
        }
        
        # Extract SOH values from both old and new datasets.
        soh_values = []
        for idx, row in self.data.iterrows():
            if 'soh_percent' in row and pd.notna(row['soh_percent']):
                soh_values.append(float(row['soh_percent']))
            elif 'soh_percentual' in row and pd.notna(row['soh_percentual']):
                soh_values.append(float(row['soh_percentual']))
        
        if soh_values:
            stats_dict['minimum_soh'] = min(soh_values)
            stats_dict['maximum_soh'] = max(soh_values)
            stats_dict['average_soh'] = np.mean(soh_values)
            if len(soh_values) > 1:
                stats_dict['total_degradation'] = soh_values[0] - soh_values[-1]
        
        # Extract cycle count.
        cycle_column = 'cycle_count' if 'cycle_count' in self.data.columns else 'ciclos' if 'ciclos' in self.data.columns else None
        if cycle_column:
            cycle_data = self.data[cycle_column].dropna()
            if not cycle_data.empty:
                stats_dict['total_cycles'] = float(cycle_data.iloc[-1]) if len(cycle_data) > 0 else None
        
        return stats_dict
    
    def generate_report(self):
        """Print a formatted report with battery health estimates."""
        print("\n" + "="*60)
        print("BATTERY HEALTH AND REMAINING USEFUL LIFE REPORT")
        print("="*60)
        
        # Basic statistics.
        stats = self.get_statistics()
        if stats:
            print("\n📊 DATASET STATISTICS:")
            print(f"   Period: {stats['period_start']} to {stats['period_end']}")
            print(f"   Total samples: {stats['total_samples']}")
            if stats['total_cycles']:
                print(f"   Total cycles: {stats['total_cycles']:.0f}")
            if stats['minimum_soh']:
                print(f"   Minimum SOH: {stats['minimum_soh']:.1f}%")
                print(f"   Average SOH: {stats['average_soh']:.1f}%")
                print(f"   Total degradation: {stats['total_degradation']:.1f}%")
        
        # Current SOH.
        current_soh = self.calculate_current_soh()
        print(f"\n🔋 CURRENT BATTERY HEALTH (SOH):")
        if current_soh:
            print(f"   {current_soh:.1f}%")
            if current_soh < 70:
                print("   ⚠️  CRITICAL: Battery below 70% - near end of life")
            elif current_soh < 80:
                print("   ⚠️  WARNING: Battery degraded - consider replacement")
            elif current_soh < 90:
                print("   ✓ Normal: Battery with moderate degradation")
            else:
                print("   ✓ Excellent: Healthy battery")
        else:
            print("   Could not calculate SOH")
        
        # Degradation rate.
        degradation = self.estimate_degradation_rate()
        if degradation:
            print(f"\n📉 DEGRADATION RATE:")
            linear = degradation['linear']
            print(f"   Linear model (R² = {linear['r2']:.3f}):")
            print(f"   - {linear['rate_daily']:.3f}% per day")
            print(f"   - {linear['rate_monthly']:.2f}% per month")
            print(f"   - {linear['rate_yearly']:.2f}% per year")
            
            if degradation['exponential'] and degradation['exponential']['r2']:
                print(f"\n   Exponential model (R² = {degradation['exponential']['r2']:.3f}):")
                print(f"   - Rate: {degradation['exponential']['rate']:.5f}")
            
            if degradation['cycle_based'] and degradation['cycle_based']['rate_per_cycle']:
                print(f"\n   Cycle-based model (R² = {degradation['cycle_based']['r2']:.3f}):")
                print(f"   - {degradation['cycle_based']['rate_per_cycle']:.4f}% per cycle")
                if degradation['cycle_based']['estimated_cycles_to_eol']:
                    print(f"   - Estimated cycles to EOL: {degradation['cycle_based']['estimated_cycles_to_eol']:.0f}")
        
        # Remaining useful life.
        rul = self.estimate_remaining_useful_life()
        if rul:
            days = rul['days_remaining']
            print(f"\n⏰ REMAINING USEFUL LIFE (RUL):")
            print(f"   Threshold considered: {rul['eol_threshold']}%")
            if days == float('inf') or days > 36500:
                print("   Remaining: > 100 years (degradation rate is negligible)")
            else:
                print(f"   Remaining days: {days:.0f} days")
                print(f"   Remaining months: {rul['months_remaining']:.1f} months")
                print(f"   Remaining years: {rul['years_remaining']:.2f} years")
                if rul['estimated_eol_date']:
                    print(f"   Estimated EOL date: {rul['estimated_eol_date'].strftime('%Y-%m-%d')}")
        
        print("\n" + "="*60)
        print("NOTES:")
        print("- EOL (End of Life) = SOH ≤ 70% (industry standard)")
        print("- Accuracy depends on the quantity and quality of historical data")
        print("- At least 30 days of data is recommended for more reliable estimates")
        print("="*60)
    
    def _r_squared(self, y_true, y_pred):
        """Calculate the coefficient of determination, R²."""
        ss_res = np.sum((y_true - y_pred) ** 2)
        ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)
        return 1 - (ss_res / ss_tot) if ss_tot != 0 else 0


def plot_results(estimator, output_file=None):
    """Generate visualization plots for battery health estimates."""
    try:
        import matplotlib.pyplot as plt
        import matplotlib.dates as mdates
        
        fig, axes = plt.subplots(2, 2, figsize=(12, 10))
        fig.suptitle('Battery Health Analysis', fontsize=14, fontweight='bold')
        
        # 1. SOH trend over time.
        ax1 = axes[0, 0]
        soh_column = 'soh_percent' if 'soh_percent' in estimator.data.columns else 'soh_percentual' if 'soh_percentual' in estimator.data.columns else None
        if 'timestamp' in estimator.data.columns and soh_column:
            ax1.plot(estimator.data['timestamp'], estimator.data[soh_column], 
                    'b-o', markersize=4, linewidth=1, label='Measured data')
            
            # Future prediction.
            future = estimator.predict_future_soh(days_ahead=180)
            if future:
                last_date = estimator.data['timestamp'].iloc[-1]
                future_dates = [last_date + timedelta(days=int(d)) for d in future['days']]
                ax1.plot(future_dates, future['soh'], 'r--', linewidth=2, label='Linear prediction')
                ax1.axhline(y=70, color='r', linestyle=':', linewidth=1, label='End of life (70%)')
            
            ax1.set_xlabel('Date')
            ax1.set_ylabel('SOH (%)')
            ax1.set_title('Battery Health Trend')
            ax1.legend()
            ax1.grid(True, alpha=0.3)
            ax1.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m'))
            plt.setp(ax1.xaxis.get_majorticklabels(), rotation=45)
        
        # 2. Degradation by cycle count.
        ax2 = axes[0, 1]
        cycle_column = 'cycle_count' if 'cycle_count' in estimator.data.columns else 'ciclos' if 'ciclos' in estimator.data.columns else None
        if cycle_column and soh_column:
            cycle_data = estimator.data.dropna(subset=[cycle_column, soh_column])
            if not cycle_data.empty:
                ax2.scatter(cycle_data[cycle_column], cycle_data[soh_column], 
                          alpha=0.6, label='Data')
                
                # Linear regression.
                cycles = cycle_data[cycle_column].values
                soh = cycle_data[soh_column].values
                z = np.polyfit(cycles, soh, 1)
                p = np.poly1d(z)
                ax2.plot(cycles, p(cycles), 'r-', label=f'Trend: {z[0]:.3f}%/cycle')
                ax2.axhline(y=70, color='r', linestyle=':', linewidth=1)
                
                ax2.set_xlabel('Charge Cycles')
                ax2.set_ylabel('SOH (%)')
                ax2.set_title('Cycle-Based Degradation')
                ax2.legend()
                ax2.grid(True, alpha=0.3)
        
        # 3. SOH distribution.
        ax3 = axes[1, 0]
        if soh_column:
            soh_values = estimator.data[soh_column].dropna()
            ax3.hist(soh_values, bins=20, edgecolor='black', alpha=0.7)
            ax3.axvline(x=soh_values.mean(), color='r', linestyle='--', 
                       label=f'Mean: {soh_values.mean():.1f}%')
            ax3.axvline(x=soh_values.iloc[-1], color='g', linestyle='--', 
                       label=f'Current: {soh_values.iloc[-1]:.1f}%')
            ax3.set_xlabel('SOH (%)')
            ax3.set_ylabel('Frequency')
            ax3.set_title('SOH Distribution')
            ax3.legend()
            ax3.grid(True, alpha=0.3)
        
        # 4. Remaining useful life.
        ax4 = axes[1, 1]
        rul = estimator.estimate_remaining_useful_life()
        if rul and rul['days_remaining'] != float('inf'):
            # Bar chart for RUL.
            categories = ['Days', 'Months', 'Years']
            values = [rul['days_remaining'], rul['months_remaining'], rul['years_remaining']]
            colors = ['blue', 'orange', 'green']
            bars = ax4.bar(categories, values, color=colors, alpha=0.7)
            
            # Add values on bars.
            for bar, val in zip(bars, values):
                ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                        f'{val:.1f}', ha='center', va='bottom')
            
            ax4.set_ylabel('Remaining Time')
            ax4.set_title(f'Remaining Useful Life (to {rul["eol_threshold"]}%)')
            ax4.grid(True, alpha=0.3, axis='y')
            
            # Additional text.
            ax4.text(0.5, -0.2, f'Current SOH: {rul["current_soh"]:.1f}%\n'
                    f'Degradation rate: {rul["degradation_rate_yearly"]:.2f}%/year',
                    transform=ax4.transAxes, ha='center', fontsize=10,
                    bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
        
        plt.tight_layout()
        
        if output_file:
            plt.savefig(output_file, dpi=150, bbox_inches='tight')
            print(f"\n📈 Plot saved to: {output_file}")
        else:
            plt.show()
            
    except ImportError:
        print("\n⚠️  Matplotlib is not installed. Install it with: pip install matplotlib")
    except Exception as e:
        print(f"\n⚠️  Error generating plots: {e}")


def main():
    """Parse command-line arguments and run the analysis workflow."""
    parser = argparse.ArgumentParser(description='Estimate battery health and remaining useful life from historical data')
    parser.add_argument('data_file', type=str, help='CSV or JSON file containing historical battery data')
    parser.add_argument('--plot', action='store_true', help='Generate plots for the estimates')
    parser.add_argument('--plot-output', type=str, default='battery_analysis.png', help='Output file for the plot image')
    parser.add_argument('--eol', type=float, default=70, help='SOH threshold for end of life (default: 70%%)')
    parser.add_argument('--json', action='store_true', help='Emit output in JSON format')
    
    args = parser.parse_args()
    
    # Check whether the input file exists.
    if not Path(args.data_file).exists():
        print(f"Error: File not found: {args.data_file}")
        return
    
    # Create the estimator.
    estimator = BatteryEstimator(args.data_file)
    
    if estimator.data.empty:
        print("Error: Could not load data or the dataset is empty")
        return
    
    if args.json:
        # JSON output.
        result = {
            'current_soh': estimator.calculate_current_soh(),
            'degradation': estimator.estimate_degradation_rate(),
            'rul': estimator.estimate_remaining_useful_life(eol_threshold=args.eol),
            'statistics': estimator.get_statistics()
        }
        print(json.dumps(result, indent=2, default=str))
    else:
        # Formatted text report.
        estimator.generate_report()
        
        if args.plot:
            plot_results(estimator, args.plot_output)


if __name__ == "__main__":
    main()